### ISSUE TITLE
Problem during validation: install versus package.

### ISSUE THREAD

**Issue by victornoel** [roboconf/roboconf-maven-plugin#2]
Hi,

I'm trying to compile the following roboconf projects using maven: https://github.com/petalslink/petals-virtual-container/.

I just type "mvn clean package" into the parent directory and I get the following error:
```
[INFO] --- roboconf-maven-plugin:0.5:validate-application (default-validate-application) @ pvc-soa-app-sample ---
[INFO] Generating a report for validation errors under target/roboconf/roboconf-validation.txt
[ERROR] [ conversion ] A configuration file could not be read. File location: /home/vnoel/Linagora/Petals/dev/git/petals-virtual-container/pvc-soa-app-sample/target/roboconf-model/graph/petals-pvc/main.graph. See main.graph, line 0.
[ERROR] [ conversion ] The graph(s) could not be built.
```

If I use "mvn clean install", it works without problem, and furthermore, the next time I do "mvn clean package" it works too.

I suspect there is something wrong on how are dependencies exploited in roboconf-maven-plugin…

**Comment by vincent-zurczak** [comment]
Hi,

First, and this is my fault, we do not use this repository anymore for the Maven plug-in.
We use the one of the [platform](https://github.com/roboconf/roboconf-platform) since the Maven plug-in is now part of it. I will disable issues once we solve this problem. :smiling_imp: 

Then, I remember the **pvc-soa-app-sample** module is one of the last ones in the build.
So, you packaged its dependencies but you did not installed them in your local repository. In fact, if you make the test with Java modules, you will see the same thing happen.

`mvn package` fails if the built modules have dependencies between them.
So, this is not a bug with the Robocnf plug-in, but with Maven itself (if we can call it a bug).

With such cases, you have to run `mvn clean install` on the project before working on modules.

**Comment by victornoel** [comment]
Ok, for the repository, it's noted :)

As for the problem with maven, it's a known situation with maven plugins, for example, the java compiler from maven is able to understand the difference between a dependency in the reactor and a dependency in the repository: it will look for dependencies classes in the right place depending on the situation.

I think roboconf could be able to do the same thing :)
Meanwhile, it could be interesting to log some kind of hint on why there is an error, so that people can directly understand that the roboconf plugin does not support reactor builds.

Thanks, I will close this bug here and let you open another one in platform to support reactor build if you desire so.

**Comment by vincent-zurczak** [comment]
Could you create the issue about reactor builds please?
I will take a look at it when I find some time. Thanks!
